FROM golang:1.25-trixie AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -trimpath -o reminder .

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /app/reminder /app/reminder
EXPOSE 8080
CMD [ "/app/reminder" ]
